name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'public/workshops/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
        env:
          VITE_ASTRA_TOKEN: ${{ secrets.VITE_ASTRA_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
